"""empty message

Revision ID: 161cad0ace47
Revises: 
Create Date: 2026-07-18 12:40:07.816493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161cad0ace47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Unique identifier for user'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='User first name'),
    sa.Column('last_name', sa.String(length=255), nullable=False, comment='User last name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when user was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when user was last updated'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Unique identifier for learning session'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='User who owns this session'),
    sa.Column('transcript', sa.Text(), nullable=True, comment='Generated transcript from uploaded recording'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when session was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when session was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.Uuid(), nullable=False, comment='Unique identifier for attachment'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Session this attachment belongs to'),
    sa.Column('attachment_type', sa.String(length=50), nullable=False, comment='Type of attachment (audio, pdf, image, etc.)'),
    sa.Column('storage_loc', sa.String(length=500), nullable=False, comment='Object storage path/location'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when attachment was uploaded'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when attachment metadata changed'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('evaluations',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False, comment='Unique identifier for evaluation'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Session being evaluated'),
    sa.Column('evaluation_details', sa.JSON(), nullable=False, comment='AI evaluation output stored as JSON'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when evaluation was generated'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_table('topics',
    sa.Column('topic_id', sa.Uuid(), nullable=False, comment='Unique identifier for topic'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Session this topic belongs to'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Topic name'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI generated topic summary'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when topic was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when topic was last updated'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    op.drop_table('evaluations')
    op.drop_table('attachments')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
