"""added passwords

Revision ID: 037f87de9912
Revises: 2c15bb81d84a
Create Date: 2026-07-27 01:08:18.954219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037f87de9912'
down_revision: Union[str, Sequence[str], None] = '2c15bb81d84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.Uuid(), nullable=False, comment='hashed password'))
    op.create_unique_constraint(None, 'users', ['hashed_password'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
