"""removed hashed password

Revision ID: 17f99a4fef19
Revises: 037f87de9912
Create Date: 2026-07-31 17:20:18.028334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f99a4fef19'
down_revision: Union[str, Sequence[str], None] = '037f87de9912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False, comment='Unique identifier for evaluation'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Session being evaluated'),
    sa.Column('evaluation_details', sa.JSON(), nullable=False, comment='AI evaluation output stored as JSON'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when evaluation was generated'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.drop_constraint(op.f('users_hashed_password_key'), 'users', type_='unique')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.UUID(), autoincrement=False, nullable=False, comment='hashed password'))
    op.create_unique_constraint(op.f('users_hashed_password_key'), 'users', ['hashed_password'], postgresql_nulls_not_distinct=False)
    op.drop_table('evaluations')
    # ### end Alembic commands ###
