"""added mime type column to attachment model

Revision ID: 2aad180bca46
Revises: 17f99a4fef19
Create Date: 2026-08-01 19:42:06.805853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aad180bca46'
down_revision: Union[str, Sequence[str], None] = '17f99a4fef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('mime_type', sa.String(length=50), nullable=False, comment='Label telling other systems the format of a file'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'mime_type')
    # ### end Alembic commands ###
