"""reset tables

Revision ID: 2c15bb81d84a
Revises: 
Create Date: 2026-07-26 01:08:15.860022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c15bb81d84a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Unique identifier for user'),
    sa.Column('auth_id', sa.String(length=255), nullable=False, comment='authentication id used in jwt tokens'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='User first name'),
    sa.Column('last_name', sa.String(length=255), nullable=False, comment='User last name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when user was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when user was last updated'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Unique identifier for learning session'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='User who owns this session'),
    sa.Column('transcript', sa.Text(), nullable=True, comment='Generated transcript from uploaded recording'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when session was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when session was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.Uuid(), nullable=False, comment='Unique identifier for attachment'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Session this attachment belongs to'),
    sa.Column('attachment_type', sa.String(length=50), nullable=False, comment='Type of attachment (audio, pdf, image, etc.)'),
    sa.Column('storage_loc', sa.String(length=500), nullable=False, comment='Object storage path/location'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when attachment was uploaded'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when attachment metadata changed'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('topics',
    sa.Column('topic_id', sa.Uuid(), nullable=False, comment='Unique identifier for topic'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Session this topic belongs to'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Topic name'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI generated topic summary'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when topic was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp when topic was last updated'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    op.drop_table('attachments')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
