"""empty message

Revision ID: 4fd7909cf990
Revises: d21d7495d849
Create Date: 2026-08-23 20:06:41.357107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd7909cf990'
down_revision: Union[str, Sequence[str], None] = 'd21d7495d849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'storage_loc',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_comment='Object storage path/location',
               existing_nullable=False)
    op.alter_column('topics', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='AI generated Topic name',
               existing_comment='Topic name',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Topic name',
               existing_comment='AI generated Topic name',
               existing_nullable=False)
    op.alter_column('attachments', 'storage_loc',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_comment='Object storage path/location',
               existing_nullable=False)
    # ### end Alembic commands ###
