"""moved transcripts to it's own table

Revision ID: d21d7495d849
Revises: 2aad180bca46
Create Date: 2026-08-02 12:38:30.952919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21d7495d849'
down_revision: Union[str, Sequence[str], None] = '2aad180bca46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('transcript_id', sa.Uuid(), nullable=False, comment='Unique identifier for a transcript'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='Session which oens this transcript'),
    sa.Column('content', sa.Text(), nullable=False, comment='content of the transcript'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp the transcript was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='Timestamp the transcript was last updated'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transcript_id', 'session_id')
    )
    op.drop_column('sessions', 'transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True, comment='Generated transcript from uploaded recording'))
    op.drop_table('transcripts')
    # ### end Alembic commands ###
